name: 🛜 Status - Workflows

on:
  issues:
    types: [opened, edited, labeled, closed]
  pull_request:
    types: [opened, closed, synchronize]
    branches: ['**']
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  fetch-workflows:
    name: 🌐 Fetch Workflows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 📊 Fetch Workflow Statuses
        id: fetch-status
        run: |
          # Fetch all workflows using gh CLI
          gh workflow list --all --json name,id,state > workflows.json

          # Parse counts
          total=$(jq '. | length' workflows.json)
          running=$(jq '[.[] | select(.state == "in_progress")] | length' workflows.json)
          successful=$(jq '[.[] | select(.state == "completed")] | length' workflows.json)

          # Generate Markdown Table for Workflows
          echo "| Name | ID | State |" > workflows_table.md
          echo "|------|----|-------|" >> workflows_table.md
          jq -r '.[] | "| \(.name) | \(.id) | \(.state) |"' workflows.json >> workflows_table.md

          # Save workflow output to environment variables and summary
          gh workflow list --all > workflows_output.txt
          cat workflows_output.txt >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY

          # Export environment variables
          echo "TOTAL_WORKFLOWS=$total" >> $GITHUB_ENV
          echo "RUNNING_WORKFLOWS=$running" >> $GITHUB_ENV
          echo "SUCCESSFUL_WORKFLOWS=$successful" >> $GITHUB_ENV
          echo "WORKFLOWS_OUTPUT<<EOF" >> $GITHUB_ENV
          cat workflows_output.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

  comment:
    name: 💬 Comment on Issue/PR
    needs: [fetch-workflows]
    runs-on: ubuntu-latest

    steps:
      - name: 🗣️ Add Status Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number || github.event.issue.number }}
          body: |
            > [!TIP]
            > 
            ### 📝 Workflow Status Update
            Hi there! Here's the current status of the workflows:

            - **Total Workflows:** ${{ env.TOTAL_WORKFLOWS }}
            - **Running Workflows:** ${{ env.RUNNING_WORKFLOWS }}
            - **Successful Workflows:** ${{ env.SUCCESSFUL_WORKFLOWS }}

            ### 🔗 All Workflows
            ```text
            ${{ env.WORKFLOWS_OUTPUT }}
            ```

            ### 📋 Workflows Summary Table
            | Name | ID | State |
            |------|----|-------|
            ${{ steps.fetch-status.outputs.workflows_table }}
