name: Automated PR Manager

on:
  push:
    branches-ignore:
      - "master"
      - "old"
      - "readme-2022"
      - "Automation"
      - "Best-Readme-Ever"
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  create_pr_repo_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create or Open A PR
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "[Bot] Automated Pull Request [Bot]."
          pr_template: "This Pull Request Was Automated by github-actions-robot."
          pr_reviewer: "offensive-vk"
          pr_draft: false
